/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCertificateRouteImport } from './routes/_authenticated/certificate'
import { Route as AuthenticatedFinalAssessmentRouteImport } from './routes/_authenticated/final-assessment'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnModuleIdRouteImport } from './routes/learn.$moduleId'
import { Route as ApiPublicCertificatesCertificateIdRouteImport } from './routes/api/public/certificates.$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificateRoute =
  AuthenticatedCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinalAssessmentRoute =
  AuthenticatedFinalAssessmentRouteImport.update({
    id: '/final-assessment',
    path: '/final-assessment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnModuleIdRoute = LearnModuleIdRouteImport.update({
  id: '/learn/$moduleId',
  path: '/learn/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificatesCertificateIdRoute =
  ApiPublicCertificatesCertificateIdRouteImport.update({
    id: '/api/public/certificates/$certificateId',
    path: '/api/public/certificates/$certificateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/verify': typeof VerifyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/final-assessment': typeof AuthenticatedFinalAssessmentRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/certificates/$certificateId': typeof ApiPublicCertificatesCertificateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/verify': typeof VerifyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/certificate': typeof AuthenticatedCertificateRoute
  '/final-assessment': typeof AuthenticatedFinalAssessmentRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn': typeof LearnIndexRoute
  '/api/public/certificates/$certificateId': typeof ApiPublicCertificatesCertificateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/partners': typeof PartnersRoute
  '/programme': typeof ProgrammeRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/certificate': typeof AuthenticatedCertificateRoute
  '/_authenticated/final-assessment': typeof AuthenticatedFinalAssessmentRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/learn/$moduleId': typeof LearnModuleIdRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/certificates/$certificateId': typeof ApiPublicCertificatesCertificateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/partners'
    | '/programme'
    | '/verify'
    | '/account'
    | '/certificate'
    | '/final-assessment'
    | '/partner'
    | '/learn/$moduleId'
    | '/learn/'
    | '/api/public/certificates/$certificateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/partners'
    | '/programme'
    | '/verify'
    | '/account'
    | '/certificate'
    | '/final-assessment'
    | '/partner'
    | '/learn/$moduleId'
    | '/learn'
    | '/api/public/certificates/$certificateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/partners'
    | '/programme'
    | '/verify'
    | '/_authenticated/account'
    | '/_authenticated/certificate'
    | '/_authenticated/final-assessment'
    | '/_authenticated/partner'
    | '/learn/$moduleId'
    | '/learn/'
    | '/api/public/certificates/$certificateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PartnersRoute: typeof PartnersRoute
  ProgrammeRoute: typeof ProgrammeRoute
  VerifyRoute: typeof VerifyRoute
  LearnModuleIdRoute: typeof LearnModuleIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiPublicCertificatesCertificateIdRoute: typeof ApiPublicCertificatesCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificate': {
      id: '/_authenticated/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof AuthenticatedCertificateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/final-assessment': {
      id: '/_authenticated/final-assessment'
      path: '/final-assessment'
      fullPath: '/final-assessment'
      preLoaderRoute: typeof AuthenticatedFinalAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$moduleId': {
      id: '/learn/$moduleId'
      path: '/learn/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof LearnModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificates/$certificateId': {
      id: '/api/public/certificates/$certificateId'
      path: '/api/public/certificates/$certificateId'
      fullPath: '/api/public/certificates/$certificateId'
      preLoaderRoute: typeof ApiPublicCertificatesCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCertificateRoute: typeof AuthenticatedCertificateRoute
  AuthenticatedFinalAssessmentRoute: typeof AuthenticatedFinalAssessmentRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCertificateRoute: AuthenticatedCertificateRoute,
  AuthenticatedFinalAssessmentRoute: AuthenticatedFinalAssessmentRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PartnersRoute: PartnersRoute,
  ProgrammeRoute: ProgrammeRoute,
  VerifyRoute: VerifyRoute,
  LearnModuleIdRoute: LearnModuleIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiPublicCertificatesCertificateIdRoute:
    ApiPublicCertificatesCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
