packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  sharp: false

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@nestjs/core'
  - '@swc/core'
  - prisma
  - esbuild
  - msgpackr-extract
