INSERT INTO public.assessments (slug, module_id, kind, title_en, title_rw, pass_mark, max_attempts)
VALUES ('final-assessment', NULL, 'final',
 'UZA Empower final assessment', 'Ikizamini cya nyuma cya UZA Empower', 80, 3)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.questions (slug, assessment_id, prompt_en, prompt_rw, options_en, options_rw, correct_index, explain_en, explain_rw, sort_order)
SELECT v.slug, a.id, v.prompt_en, v.prompt_rw, v.options_en::jsonb, v.options_rw::jsonb, v.correct_index, v.explain_en, v.explain_rw, v.sort_order
FROM public.assessments a, (VALUES
 ('fa-01','You earn RWF 18,000 today. Which money is truly yours to spend?',
  'Uyu munsi winjije 18,000 RWF. Ni ayahe mafaranga koko ari ayawe yo gukoresha?',
  '["All 18,000","What remains after charging, the instalment, savings and other costs","Half of it","Nothing until the loan ends"]',
  '["Yose 18,000","Asigaye nyuma yo kwishyura umuriro, ubwishyu, kuzigama n''ibindi biciro","Kimwe cya kabiri","Nta na yamwe kugeza inguzanyo irangiye"]',
  1,'Income is not profit. Costs and the instalment come out first.','Amafaranga yinjiye si inyungu. Ibiciro n''ubwishyu bibanza gukurwamo.',1),
 ('fa-02','Why must business money and household money be separated?',
  'Kuki amafaranga y''ubucuruzi n''ay''urugo agomba gutandukanywa?',
  '["Because the bank forbids spending","So the instalment and running costs are never eaten by mistake","To hide money from family","There is no real reason"]',
  '["Kuko banki ibuza gukoresha amafaranga","Kugira ngo ubwishyu n''ibiciro by''akazi bitariwe mu makosa","Kugira ngo uhishe amafaranga umuryango","Nta mpamvu ifatika ihari"]',
  1,'Separation protects the instalment first, then the household.','Gutandukanya birinda ubwishyu mbere na mbere, hanyuma urugo.',2),
 ('fa-03','What is the minimum client contribution in the UZA Empower structure?',
  'Umusanzu ntarengwa muto w''umukiriya muri gahunda ya UZA Empower ni uwuhe?',
  '["RWF 100,000","RWF 500,000","RWF 2,500,000","No contribution is needed"]',
  '["100,000 RWF","500,000 RWF","2,500,000 RWF","Nta musanzu ukenewe"]',
  1,'RWF 500,000 plus completing this programme substitutes for driver equity.','500,000 RWF hamwe no kurangiza aya mahugurwa bisimbura umutungo w''umushoferi.',3),
 ('fa-04','In a reducing balance loan, interest is charged on:',
  'Mu nguzanyo y''umwenda ugabanuka, inyungu ibarwa ku:',
  '["The original amount forever","What you still owe today","Your daily income","The vehicle price plus insurance"]',
  '["Umubare wa mbere burundu","Ibyo ukirimo uyu munsi","Amafaranga winjiza ku munsi","Igiciro cy''imodoka n''ubwishingizi"]',
  1,'As the balance falls, the interest portion falls with it.','Uko umwenda ugabanuka, ni ko inyungu igabanuka.',4),
 ('fa-05','You cannot pay the full instalment this month. What is correct?',
  'Ntushobora kwishyura ubwishyu bwose uku kwezi. Ikihe gikwiye?',
  '["Say nothing and wait","Tell the bank early and agree a plan before the due date","Borrow from a moneylender at any rate","Stop driving until next month"]',
  '["Ntugire icyo uvuga utegereze","Menyesha banki hakiri kare munumvikane ku gahunda mbere y''itariki","Guhera ku mucuruzi w''inguzanyo ku nyungu iyo ariyo yose","Guhagarika gutwara kugeza ukwezi gutaha"]',
  1,'Early disclosure keeps you bankable; silence creates default.','Kumenyesha hakiri kare bikurinda; guceceka bizana gutsindwa n''umwenda.',5),
 ('fa-06','What happens if a loan goes into default?',
  'Bigenda bite iyo inguzanyo itishyuwe (default)?',
  '["Nothing changes","Penalties grow, your credit record is damaged and the asset can be taken","The bank forgives the balance","The instalment is cancelled"]',
  '["Nta kintu gihinduka","Ibihano byiyongera, amateka yawe ya banki yangirika, umutungo ushobora kwamburwa","Banki ikubabarira umwenda","Ubwishyu buhagarika"]',
  1,'Default costs money, reputation and eventually the vehicle.','Gutsindwa n''umwenda bikutwara amafaranga, izina, n''imodoka.',6),
 ('fa-07','Saving RWF 500,000 in 10 months means putting aside about:',
  'Kuzigama 500,000 RWF mu mezi 10 bisobanura kubika hafi:',
  '["RWF 5,000 a month","RWF 50,000 a month","RWF 150,000 a month","RWF 500 a day"]',
  '["5,000 RWF ku kwezi","50,000 RWF ku kwezi","150,000 RWF ku kwezi","500 RWF ku munsi"]',
  1,'500,000 divided by 10 months is 50,000 a month, about 1,700 a day.','500,000 bigabanyijwe n''amezi 10 ni 50,000 ku kwezi, hafi 1,700 ku munsi.',7),
 ('fa-08','Which record makes a bank trust you most?',
  'Iyihe nyandiko ituma banki ikwizera kurusha izindi?',
  '["A verbal promise","Months of consistent daily income and expense records plus MoMo history","A new phone","A friend''s recommendation only"]',
  '["Isezerano ry''akanwa","Amezi y''inyandiko zihoraho z''amafaranga yinjira n''asohoka hamwe n''amateka ya MoMo","Telefone nshya","Inama y''inshuti gusa"]',
  1,'Evidence over promises: consistent records are the credential.','Ibimenyetso kuruta amasezerano: inyandiko zihoraho ni impamyabushobozi.',8),
 ('fa-09','A one-page business plan must at minimum show:',
  'Gahunda y''ubucuruzi ku rupapuro rumwe igomba nibura kugaragaza:',
  '["Your dream car","Expected income, costs, instalment and what remains","Your family tree","Only the loan amount"]',
  '["Imodoka wifuza","Amafaranga witeze, ibiciro, ubwishyu, n''ibisigara","Umuryango wawe","Umubare w''inguzanyo gusa"]',
  1,'A plan is arithmetic you can defend, not a wish.','Gahunda ni imibare ushobora kuyisobanura, si icyifuzo.',9),
 ('fa-10','Insurance and compliance papers should be treated as:',
  'Ubwishingizi n''impapuro z''ubuziranenge bigomba gufatwa nka:',
  '["An optional extra","A fixed monthly cost planned for in advance","Something to buy after a problem","The bank''s responsibility"]',
  '["Ikintu cy''ubushake","Igiciro gihoraho cya buri kwezi giteganywa mbere","Ikintu ugura nyuma y''ikibazo","Inshingano za banki"]',
  1,'Planned costs do not become emergencies.','Ibiciro biteganyijwe ntibihinduka ibyihutirwa.',10),
 ('fa-11','The healthiest daily charging habit for the battery is to keep it around:',
  'Ingeso nziza yo kuzuza umuriro ku munsi ni kugumisha bateri hafi:',
  '["0-100% every day","20-80% for daily use","Always 100%","Below 10%"]',
  '["0-100% buri munsi","20-80% ku mikoreshwa ya buri munsi","Buri gihe 100%","Munsi ya 10%"]',
  1,'Daily 20-80% charging extends battery life; full 100% only when needed for a long trip.','Kuzuza 20-80% ku munsi birambura ubuzima bwa bateri; 100% gusa iyo ugiye urugendo rurerure.',11),
 ('fa-12','Regenerative braking means:',
  'Amaferi asubiza ingufu bisobanura:',
  '["The brakes charge faster when hot","Slowing down returns some energy to the battery","The car brakes by itself always","Brake pads never wear"]',
  '["Amaferi yuzura vuba iyo ashyushye","Kugabanya umuvuduko bisubiza ingufu muri bateri","Imodoka ihagarara yonyine buri gihe","Ibyuma by''amaferi ntibishira"]',
  1,'Smooth deceleration recovers energy and saves the brakes.','Kugabanya umuvuduko buhoro bisubiza ingufu kandi birinda amaferi.',12),
 ('fa-13','Compared with a petrol sedan, an EV''s cost per kilometre is usually:',
  'Ugereranyije n''imodoka ya lisansi, igiciro kuri kilometero mu modoka y''amashanyarazi ni:',
  '["Higher","Lower","Exactly the same","Impossible to know"]',
  '["Kirenze","Kiri hasi","Kingana kimwe","Ntibishoboka kumenya"]',
  1,'Electricity per kilometre costs less than fuel, and there are fewer moving parts.','Amashanyarazi kuri kilometero bihenduka kuruta lisansi, kandi ibice bigenda ni bike.',13),
 ('fa-14','Your range is dropping faster than usual in Kigali hills. First sensible action:',
  'Urugendo rwawe rurangira vuba ku misozi ya Kigali. Igikorwa cya mbere gikwiye:',
  '["Drive faster to arrive sooner","Reduce speed, use smooth acceleration and plan a charge stop","Switch the car off while rolling","Ignore it"]',
  '["Twara vuba ngo uhite ugera","Gabanya umuvuduko, ugende buhoro, uteganye aho uzuza umuriro","Zimya imodoka mu kugenda","Ntubyitaho"]',
  1,'Speed and harsh acceleration cost range; plan the charge instead.','Umuvuduko no kwihuta bikuramo urugendo; teganya kuzuza umuriro.',14),
 ('fa-15','A warning light appears on the dashboard while carrying a passenger. You should:',
  'Itara ry''iburira ryagaragaye ku dashboard ufite umugenzi. Ugomba:',
  '["Keep driving all day","Stop safely, note the message, contact the workshop before continuing","Cover the light","Restart the car repeatedly"]',
  '["Gukomeza gutwara umunsi wose","Guhagarara ahantu hatekanye, wandike ubutumwa, uhamagare garage mbere yo gukomeza","Gupfuka itara","Kuzimya no kwaka imodoka kenshi"]',
  1,'Faults get cheaper the earlier they are reported.','Ikibazo gihenduka iyo umenyekanishije hakiri kare.',15),
 ('fa-16','High-voltage components in an EV may be opened by:',
  'Ibice by''amashanyarazi menshi mu modoka y''amashanyarazi bishobora gufungurwa na:',
  '["Any driver with tools","Only a trained and certified technician","The vehicle owner at home","A fuel mechanic"]',
  '["Umushoferi wese ufite ibikoresho","Umutekinisiye wahuguwe kandi wemewe gusa","Nyir''imodoka mu rugo","Umukanishi wa lisansi"]',
  1,'High voltage kills. Isolation is a certified procedure.','Amashanyarazi menshi yica. Gutandukanya ni umurimo w''uwemewe.',16),
 ('fa-17','Which daily check belongs to an EV taxi driver before starting work?',
  'Ni ikihe genzura rya buri munsi rya nyir''imodoka y''amashanyarazi mbere yo gutangira akazi?',
  '["Engine oil level","Tyre pressure, tyre condition, brakes feel, charge level and cleanliness","Gearbox oil","Carburettor"]',
  '["Urugero rwa amavuta ya moteri","Umwuka mu mapine, uko mapine ahagaze, amaferi, urugero rw''umuriro, isuku","Amavuta ya vitesi","Karuburateri"]',
  1,'An EV has no engine oil or carburettor; tyres, brakes and charge are the daily checks.','Imodoka y''amashanyarazi ntifite amavuta ya moteri cyangwa karuburateri; mapine, amaferi n''umuriro ni ibya buri munsi.',17),
 ('fa-18','Fast charging every single day is:',
  'Kuzuza umuriro byihuse buri munsi ni:',
  '["Always best","Useful sometimes, but frequent slow charging is gentler on the battery","Impossible","Free"]',
  '["Byiza buri gihe","Bifasha rimwe na rimwe, ariko kuzuza buhoro kenshi bigirira bateri neza","Ntibishoboka","Ni ubuntu"]',
  1,'Use fast charging when the day demands it; prefer slower charging overnight.','Koresha kuzuza byihuse iyo umunsi ubisabye; ariko buhoro nijoro biruta.',18),
 ('fa-19','Leaving the vehicle at a very low charge for days:',
  'Kureka imodoka ifite umuriro muke cyane iminsi myinshi:',
  '["Is good for the battery","Can damage the battery — leave it around half charge","Has no effect","Improves range"]',
  '["Ni byiza kuri bateri","Bishobora kwangiza bateri — usige hafi kimwe cya kabiri","Nta ngaruka bifite","Byongera urugendo"]',
  1,'Long storage is safest near mid charge.','Kubika igihe kirekire ni byiza hafi ya kimwe cya kabiri.',19),
 ('fa-20','Charging at a UZA Charge Network station, the driver should first:',
  'Wuzuza umuriro kuri sitasiyo ya UZA Charge Network, umushoferi agomba mbere:',
  '["Plug in while the car is moving","Park correctly, switch off, check the cable and connector for damage, then connect",'
  || '"Leave the car unattended and go home","Pull the cable out during charging"]',
  '["Kwinjiza umugozi imodoka igenda","Parika neza, uzimye, ugenzure umugozi n''icyuma niba bitangiritse, hanyuma winjize",'
  || '"Kureka imodoka wigende","Gukuramo umugozi mu gihe kwuzuza kigenda"]',
  1,'Inspect before you connect; damaged cables are a shock and fire risk.','Genzura mbere yo kwinjiza; umugozi wangiritse utera amashanyarazi n''inkongi.',20)
) AS v(slug, prompt_en, prompt_rw, options_en, options_rw, correct_index, explain_en, explain_rw, sort_order)
WHERE a.slug = 'final-assessment'
ON CONFLICT (slug) DO NOTHING;
