/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiPublicMomoCallbackRouteImport } from './routes/api/public/momo.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMomoCallbackRoute = ApiPublicMomoCallbackRouteImport.update({
  id: '/api/public/momo/callback',
  path: '/api/public/momo/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/ops': typeof OpsRoute
  '/rider': typeof RiderRoute
  '/wallet': typeof WalletRoute
  '/api/public/momo/callback': typeof ApiPublicMomoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/ops': typeof OpsRoute
  '/rider': typeof RiderRoute
  '/wallet': typeof WalletRoute
  '/api/public/momo/callback': typeof ApiPublicMomoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/driver': typeof DriverRoute
  '/ops': typeof OpsRoute
  '/rider': typeof RiderRoute
  '/wallet': typeof WalletRoute
  '/api/public/momo/callback': typeof ApiPublicMomoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/auth'
    | '/driver'
    | '/ops'
    | '/rider'
    | '/wallet'
    | '/api/public/momo/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/auth'
    | '/driver'
    | '/ops'
    | '/rider'
    | '/wallet'
    | '/api/public/momo/callback'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/auth'
    | '/driver'
    | '/ops'
    | '/rider'
    | '/wallet'
    | '/api/public/momo/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AuthRoute: typeof AuthRoute
  DriverRoute: typeof DriverRoute
  OpsRoute: typeof OpsRoute
  RiderRoute: typeof RiderRoute
  WalletRoute: typeof WalletRoute
  ApiPublicMomoCallbackRoute: typeof ApiPublicMomoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/momo/callback': {
      id: '/api/public/momo/callback'
      path: '/api/public/momo/callback'
      fullPath: '/api/public/momo/callback'
      preLoaderRoute: typeof ApiPublicMomoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AuthRoute: AuthRoute,
  DriverRoute: DriverRoute,
  OpsRoute: OpsRoute,
  RiderRoute: RiderRoute,
  WalletRoute: WalletRoute,
  ApiPublicMomoCallbackRoute: ApiPublicMomoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
